version: "3.9"

services: 

  frontend:
    image: 'caddy:latest'
    container_name: "frontend"
    ports: 
      - 5001:443
    volumes:
      - ./frontend/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./frontend/src:/srv

  backend:
    build:
      context: ./backend
    container_name: "backend"
    ports: 
      - 5000:5000

  redis:
    image: redislabs/redisearch:latest
    container_name: "redis"
    volumes: 
      - redis_data:/data

  rechadresses:
    build:
      context: ./rechadresses
    container_name: "rechadresses"
    depends_on:
      - "redis"

volumes: 
  redis_data:
  caddy_data:
  caddy_config: